#
# Copyright (C) 2015 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=perl-test-warn
PKG_VERSION:=0.37
PKG_RELEASE:=1

PKG_SOURCE:=Test-Warn-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://cpan.metacpan.org/authors/id/B/BI/BIGJ
PKG_HASH:=98ca32e7f2f5ea89b8bfb9a0609977f3d153e242e2e51705126cb954f1a06b57
PKG_BUILD_DIR:=$(BUILD_DIR)/perl/Test-Warn-$(PKG_VERSION)

PKG_MAINTAINER:=Marcel Denia <naoir@gmx.net>
PKG_LICENSE:=GPL-1.0-or-later Artistic-1.0-Perl

include $(INCLUDE_DIR)/package.mk
include ../perlmod.mk

define Package/perl-test-warn
  SUBMENU:=Perl
  SECTION:=lang
  CATEGORY:=Languages
  TITLE:=Perl extension to test methods for warnings
  URL:=https://search.cpan.org/dist/Test-Warn/
  DEPENDS:=perl +perl-sub-uplevel +perlbase-essential +perlbase-test
endef

define Build/Configure
        $(call perlmod/Configure,,)
endef

define Build/Compile
        $(call perlmod/Compile,,)
endef

define Package/perl-test-warn/install
        $(call perlmod/Install,$(1),Test auto/Test)
endef


$(eval $(call BuildPackage,perl-test-warn))
